pipeline{
    agent any //to define which node to deploy on - any means to deploy on every server that has been defined , e.g. agent leon, joel etc to deploy on server leon and joel

    stages{
        stage('Development Environment'){ 
            steps{
                sh 'sudo systemctl stop mintbooking.service'
                sh 'chmod +x ./script/*' //makes everything in script folder executable - makes root/group/user executable
                sh './script/before_installation.sh' //use dot to run something
                sh './script/installation.sh'
                sh './script/buildservices.sh'                
                sh 'echo "Built Successfully"'
                sh 'sleep 13'       
            }
        }

        stage('Testing Environment'){
            steps{
                sh 'python3 -m pytest ./test/testing.py'
                sh 'pip3 show coverage'
                sh 'python3 -m coverage run -m pytest ./test/testing.py'
                sh 'python3 -m coverage report -m'
                sh 'echo "Testing completed Successfully"'
            }
        }
    }
}