pipeline{
    agent any //to define which node to deploy on - any means to deploy on every server that has been defined , e.g. agent leon, joel etc to deploy on server leon and joel

    stages{
        stage('Development Environment'){ //
            steps{
                sh 'chmod +x ./script/*' //makes everything in script folder executable - makes root/group/user executable
                sh './script/before_installation.sh' //use dot to run something
                sh './script/installation.sh'
                sh 'echo "Built Successfully"' 
                
                
            }
        }
    }
}